<?php
// Simple email sending using a free email service
// This is a basic solution for testing purposes

function sendEmailSimple($to, $subject, $htmlBody, $from = 'careers@sofindex.com') {
    // Log email for debugging
    $logFile = __DIR__ . '/email_log.txt';
    $logEntry = "=== EMAIL LOG ===\n";
    $logEntry .= "Date: " . date('Y-m-d H:i:s') . "\n";
    $logEntry .= "To: " . $to . "\n";
    $logEntry .= "From: " . $from . "\n";
    $logEntry .= "Subject: " . $subject . "\n";
    $logEntry .= "Body Length: " . strlen($htmlBody) . " characters\n";
    $logEntry .= "================\n\n";
    
    file_put_contents($logFile, $logEntry, FILE_APPEND | LOCK_EX);
    
    // Create email preview file for development
    $previewFile = __DIR__ . '/email_preview_' . time() . '.html';
    $previewContent = "
    <!DOCTYPE html>
    <html>
    <head>
        <title>Email Preview: $subject</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }
            .email-info { background: #fff; padding: 20px; margin-bottom: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .email-content { background: #fff; border: 1px solid #ddd; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .preview-note { background: #e3f2fd; padding: 15px; border-radius: 5px; margin-bottom: 20px; border-left: 4px solid #2196f3; }
        </style>
    </head>
    <body>
        <div class='preview-note'>
            <h3>📧 Email Preview (Development Mode)</h3>
            <p>This is a preview of the email that would be sent. In production, this would be delivered to the recipient.</p>
        </div>
        
        <div class='email-info'>
            <h3>📋 Email Details:</h3>
            <p><strong>To:</strong> $to</p>
            <p><strong>From:</strong> $from</p>
            <p><strong>Subject:</strong> $subject</p>
            <p><strong>Date:</strong> " . date('Y-m-d H:i:s') . "</p>
            <p><strong>Status:</strong> <span style='color: #ff9800;'>Preview Mode - Not Actually Sent</span></p>
        </div>
        
        <div class='email-content'>
            <h3>📄 Email Content:</h3>
            $htmlBody
        </div>
        
        <div style='text-align: center; margin-top: 30px; color: #666;'>
            <p>Generated by SOFINDEX System</p>
        </div>
    </body>
    </html>";
    
    file_put_contents($previewFile, $previewContent);
    
    // Log the preview file creation
    $previewLog = "Email preview created: $previewFile\n";
    file_put_contents($logFile, $previewLog, FILE_APPEND | LOCK_EX);
    
    // For now, return true to simulate successful email
    // In production, you would integrate with a real email service
    return true;
}

function sendApplicationEmailsSimple($application, $job) {
    require_once 'email_templates.php';
    
    // Send email to admin
    $adminEmail = 'careers@sofindex.com';
    $adminSubject = 'New Job Application: ' . $job['title'] . ' - ' . $application['full_name'];
    $adminBody = getAdminNotificationEmail($application, $job);
    
    $adminResult = sendEmailSimple($adminEmail, $adminSubject, $adminBody);
    
    // Send confirmation email to applicant
    $applicantEmail = $application['email'];
    $applicantSubject = 'Application Received - ' . $job['title'] . ' | SOFINDEX';
    $applicantBody = getUserConfirmationEmail($application, $job);
    
    $applicantResult = sendEmailSimple($applicantEmail, $applicantSubject, $applicantBody);
    
    return array(
        'admin_sent' => $adminResult,
        'applicant_sent' => $applicantResult,
        'preview_files' => array(
            'admin' => 'email_preview_' . time() . '_admin.html',
            'applicant' => 'email_preview_' . time() . '_applicant.html'
        )
    );
}
?>
